version: '3.8'

# Cathedral Architecture: Each container has one sacred duty
# Structure enforces security - no memory required

services:
  # Pure database - no modifications, no complexity
  database:
    image: arangodb:latest
    container_name: mallku-database-core
    environment:
      - ARANGO_NO_AUTH=1  # Auth happens at API layer
    volumes:
      - mallku_data:/var/lib/arangodb3
      - mallku_apps_data:/var/lib/arangodb3-apps
    networks:
      - mallku-internal
    # NO PORTS EXPOSED - this is structural security
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8529/_api/version"]
      interval: 10s
      timeout: 5s
      retries: 10  # More retries for slow systems
      start_period: 30s  # More time to initialize

  # Security layer - the only gateway
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: mallku-api-gateway
    restart: unless-stopped  # Auto-restart on failure
    depends_on:
      database:
        condition: service_healthy
    environment:
      - MALLKU_DB_HOST=database
      - MALLKU_DB_PORT=8529
      - MALLKU_API_HOST=0.0.0.0
      - MALLKU_API_PORT=8080
    ports:
      - "8080:8080"  # ONLY exposed port in entire system
    networks:
      - mallku-internal
      - mallku-external
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s  # Give API plenty of time to start

networks:
  mallku-internal:
    internal: true  # Cannot be reached from host
  mallku-external:
    # Only the API container connects here

volumes:
  mallku_data:
  mallku_apps_data:
