#!/bin/bash
# Setup Comprehensive Pre-commit Hook
# 52nd Guardian - Ensures local pre-commit matches CI behavior

echo "🔧 Setting up comprehensive pre-commit hook..."

# Check if pre-commit is installed
if ! command -v pre-commit &> /dev/null; then
    echo "❌ pre-commit not found. Please install with: pip install pre-commit"
    exit 1
fi

# Install pre-commit hooks
echo "📦 Installing pre-commit hooks..."
pre-commit install

# Get current working directory
REPO_ROOT=$(git rev-parse --show-toplevel)
HOOK_FILE="$REPO_ROOT/.git/hooks/pre-commit"

# Check if we're in a git repository
if [ ! -d "$REPO_ROOT/.git" ]; then
    echo "❌ Not in a git repository"
    exit 1
fi

# Create the comprehensive pre-commit hook
echo "🚀 Creating comprehensive pre-commit hook..."
cat > "$HOOK_FILE" << 'EOF'
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# Modified by 52nd Guardian to run --all-files for comprehensive checking
# ID: 138fd403232d2ddd5efb44317e38bf03

# Custom implementation to run all files instead of just staged
if [ -x "$(pwd)/.venv/bin/python" ]; then
    exec "$(pwd)/.venv/bin/python" -mpre_commit run --all-files
elif command -v pre-commit > /dev/null; then
    exec pre-commit run --all-files
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
EOF

# Make it executable
chmod +x "$HOOK_FILE"

echo "✅ Comprehensive pre-commit hook installed!"
echo ""
echo "ℹ️  Changes:"
echo "   - Pre-commit now runs --all-files (comprehensive checking)"
echo "   - Local behavior matches CI exactly"
echo "   - Catches all violations before pushing"
echo ""
echo "🎯 Next commit will check the entire codebase for violations"
