name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  sanctify-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Ensure Python 3.12+ with uv
        run: |
          uv venv --python=3.12 .venv
          echo ".venv/bin" >> $GITHUB_PATH
      - name: Cache uv pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
      - name: Install pre-commit
        run: uv pip install pre-commit
      - name: sync
        run: uv sync
      - name: Show versions
        run: |
          python --version
          uv --version
          pre-commit --version
      - name: Run pre-commit hooks
        run: uv run --active pre-commit run --all-files --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    needs: sanctify-code
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Ensure Python 3.12+ with uv
        run: |
          uv venv --python=3.12 .venv
          echo ".venv/bin" >> $GITHUB_PATH
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: deps-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
      - name: Install dependencies
        run: uv pip install -r pyproject.toml
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Ensure Python 3.12+ with uv
        run: |
          uv venv --python=3.12 .venv
          echo ".venv/bin" >> $GITHUB_PATH
      - name: Install coverage
        run: uv pip install coverage
      - name: Run coverage
        run: |
          coverage run -m pytest
          coverage report
